version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5434:5432"